[profile.default]
solc = "0.8.26"
src = "src"
out = "out"
script = "script"
libs = ["node_modules", "lib"]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[fuzz]
runs=1000